BiquadFilter added
- linker problem with DynamicsCompressor fixed, and constructor runs
with success

- BiquadFilter.GetFrequencyResponse() still needs to make call to labsound level

- Constructor fails with
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 00007FF729CFD50A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4618
 2: 00007FF729CA4F86 uv_loop_fork+79446
 3: 00007FF729CA5C21 uv_loop_fork+82673
 4: 00007FF72A1AF8C6 v8::V8::ToLocalEmpty+54
 5: 00007FFCF5598282 webaudio::AudioContext::CreateBiquadFilter+386 [c:\exokit\deps\exokit-bindings\webaudiocontext\src\audiocontext.cpp]:L355